// Suggested default query for the orchestration textarea.
// Everything else is computed from real ecosystem data or generated by AI agents.
export const DEMO_QUERY =
  "Find ecosystem support for an AI healthcare startup expanding into Indonesia.";
